apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-namager-issuer
spec:
  acme:
    email: liouyanyan9@126.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
          email: liouyanyan9@126.com
            name: cloudflare-api-token-secret
            key: api-token
